# Generated by Django 6.0.3 on 2026-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='expanded_argument',
        ),
        migrations.AddField(
            model_name='agentrun',
            name='openai_response_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
