# Generated by Django 6.0.3 on 2026-04-04 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_id', models.CharField(max_length=50)),
                ('sentence_id', models.CharField(blank=True, max_length=50)),
                ('anchor_offset_start', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_offset_end', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_quote', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('human', 'Human'), ('agent', 'AI Agent')], max_length=20)),
                ('annotation_type', models.CharField(choices=[('gap', 'Logical Gap'), ('error', 'Potential Error'), ('handwave', 'Handwaving'), ('unclear', 'Unclear'), ('assumption', 'Unverified Assumption'), ('info', 'Informational Note'), ('comment', 'Comment'), ('checked', 'Checked / Verified'), ('needs_review', 'Needs Review'), ('logic_mistake', 'Logic Mistake')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='agents.agentrun')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='agents.chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document')),
            ],
            options={
                'ordering': ['block_id', 'created_at'],
            },
        ),
    ]
