# Generated by Django 6.0.3 on 2026-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_annotation_v2_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='author',
            field=models.CharField(default='Human', max_length=200),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='end_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
