# Generated by Django 6.0.3 on 2026-04-04 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('original_source', models.TextField()),
                ('source_format', models.CharField(choices=[('latex', 'LaTeX'), ('markdown', 'Markdown+LaTeX')], max_length=20)),
                ('macro_table', models.JSONField(blank=True, default=dict)),
                ('theorem_env_table', models.JSONField(blank=True, default=dict)),
                ('expanded_source', models.TextField(blank=True)),
                ('source_map', models.JSONField(blank=True, default=list)),
                ('structure', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.CharField(choices=[('manual', 'Manual'), ('triage', 'Triage'), ('audit', 'Audit')], default='manual', max_length=20)),
                ('agent_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_id', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('theorem', 'Theorem'), ('lemma', 'Lemma'), ('proposition', 'Proposition'), ('corollary', 'Corollary'), ('definition', 'Definition'), ('remark', 'Remark'), ('proof', 'Proof'), ('equation', 'Display Equation'), ('figure', 'Figure'), ('section_heading', 'Section Heading'), ('list', 'List'), ('raw_latex', 'Raw LaTeX (TikZ etc.)')], max_length=30)),
                ('content_original', models.TextField()),
                ('content_expanded', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('source_offset_start', models.PositiveIntegerField(default=0)),
                ('source_offset_end', models.PositiveIntegerField(default=0)),
                ('sentences', models.JSONField(blank=True, default=list)),
                ('rendered_svg_path', models.CharField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.block')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('document', 'block_id'), name='unique_block_id_per_document')],
            },
        ),
    ]
